name: "Homebox"
description: "Open-source inventory and organization system for your home"
version: "1.0.2"
slug: "homebox"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/sysadminsmedia/homebox"
webui: "http://[HOST]:[PORT:7745]"
ingress: true
ingress_port: 7745
panel_icon: mdi:cube
startup: application
ports:
  7745/tcp: 7745
ports_description:
  7745/tcp: "Web interface"
hassio_api: false
hassio_role: default
map:
  - share:rw
options:
  allow_registration: true
  database_path: "/share/homebox/homebox.db"
  storage_path: "/share/homebox"
  auto_increment_asset_id: true
  asset_id_prefix: ""
  allow_analytics: false
  timezone: "UTC"
  create_admin_user: false
  admin_username: "admin"
  admin_password: ""
  admin_email: ""
schema:
  allow_registration: bool
  database_path: str
  storage_path: str
  auto_increment_asset_id: bool
  asset_id_prefix: str?
  allow_analytics: bool
  timezone: str
  create_admin_user: bool
  admin_username: str?
  admin_password: str?
  admin_email: str?